# Vagrant con Ubuntu 18.04 creado por Marco Rodriguez
# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  

  # Provision
  config.vm.provision :shell, :path => "bootstrap.sh"
  
  config.vm.network "forwarded_port", guest: 80, host: 8081


  end


