Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.network "private_network", ip: "192.168.33.10"

  #Fix SSH forwarded port
  config.vm.network "forwarded_port", guest: 22, host:2222, id: "ssh", auto_correct: true

  #Use Apache
  config.vm.network "forwarded_port", guest: 80, host:8081, id: "apache", auto_correct: true

  #config.vm.define "vagrant-ansible" do |vagrant-ansible|
  config.vm.provision "ansible_local" do |ansible|
    ansible.inventory_path = "vars/default.yml"
    ansible.verbose = 'vvv'
    ansible.playbook = "playbook.yml"
   end

    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
 end

